### PR TITLE
Convert from automake to cmake

### PR DESCRIPTION
**Pull request by gianlourbano**
Conversion of the build system from automake to cmake.

### CODE REVIEW

**Comment by danielinux** [comment]
Sorry I did not realize this was blocked because the tests did not run. There seems to be still a cmake-related failure on MacOS.

**Comment by gianlourbano** [comment]
yes, just updated the ci file, i think it should work now

**Comment by danielinux** [comment]
Still no luck. There's always some trial and error involved with github actions :grin:

**Comment by gianlourbano** [comment]
don't worry, i think i know where the problem is. I'll try on my macbook first

**Comment by danielinux** [comment]
MacOS test passes now

**Comment by gianlourbano** [comment]
Everything should work now. Incredible skill issue on my part, sorry

**Comment by danielinux** [comment]
:partying_face: everything works now! Thanks @gianlourbano !

Can you please squash into a single commit, there's a lot of fixups in this tree.

**Comment by gianlourbano** [comment]
I think there is a "squash and merge" option when merging, might have to click "try the new merging experience"

**Comment by danielinux** [comment]
I'd rather do it manually, I'm not sure what the web tool is doing under the hood. I'll take care of this step. I'll merge this ASAP. Thank you!

**Review by danielinux — APPROVED** [review]

**Pull request merged**
